package com.Youcode.security.enums;

public enum TypeGenre {

    ACTION,ADVENTURE,COMEDY,CRIME,DRAMA,FANTASY,HISTORICAL,HORROR,MYSTERY,PHILOSOPHICAL, POLITICAL,ROMANCE,SCIENCE_FICTION,THRILLER,URBAN, WESTERN

}
